<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:
### Hidden Layer:
### Output Layer:
### Neuron:
### Weight:
### Activation Function:
### Node Map:
### Perceptron:


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [1]:
import pandas as pd
import numpy as np
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [222]:
##### Your Code Here #####
correct_outputs= [[i] for i in df['y']]
#inputs =np.array([[0,0,1],
#                 [1,0,1],
#                 [0,1,1],
#                 [1,1,0]
#                 ])
correct_outputs

[[1], [1], [1], [0]]

In [223]:
inputs = np.array(df)
inputs

array([[0, 0, 1],
       [1, 0, 1],
       [0, 1, 1],
       [1, 1, 0]])

In [224]:
correct_outputs

[[1], [1], [1], [0]]

In [16]:
def sigmoid(x):
    return 1 / (1 +np.exp(-x))

def sigmoid_derivate(x):
    sx = sigmoid(x)
    return sx * (1-sx)

In [226]:
weights = 2 * np.random.random((3,1)) -1
weights

array([[ 0.45260867],
       [ 0.14945629],
       [-0.16654099]])

In [227]:
weighted_sum = np.dot(inputs, weights)
weighted_sum

array([[-0.16654099],
       [ 0.28606768],
       [-0.0170847 ],
       [ 0.60206496]])

In [228]:
activated_output = sigmoid(weighted_sum)
activated_output

array([[0.45846072],
       [0.57103316],
       [0.49572893],
       [0.64612859]])

In [229]:
error = correct_outputs - activated_output
error

array([[ 0.54153928],
       [ 0.42896684],
       [ 0.50427107],
       [-0.64612859]])

In [230]:
adjustments = error * sigmoid_derivate(weighted_sum)
adjustments

array([[ 0.13445039],
       [ 0.10507727],
       [ 0.12605857],
       [-0.147735  ]])

In [231]:
weights += np.dot(inputs.T, adjustments)
weights

array([[0.40995093],
       [0.12777986],
       [0.19904524]])

In [232]:
# Update our weights 10,000 times - (fingers crossed that this process reduces error)
for iteration in range(10000):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(inputs, weights)
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # Cac error
    error = correct_outputs - activated_output
    
    adjustments = error * sigmoid_derivate(weighted_sum)
    
    # Update the Weights
    weights += np.dot(inputs.T, adjustments)
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)

Weights after training
[[-2.40969098]
 [-2.4107678 ]
 [ 7.49022453]]
Output after training
[[0.99944175]
 [0.9938215 ]
 [0.99381489]
 [0.007999  ]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [3]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [4]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]

test_X = diabetes[['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age']]

In [5]:
from sklearn import preprocessing

x = test_X.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
df = pd.DataFrame(x_scaled)
df

0         1         2         3         4         5         6  \
0    0.352941  0.743719  0.590164  0.353535  0.000000  0.500745  0.234415   
1    0.058824  0.427136  0.540984  0.292929  0.000000  0.396423  0.116567   
2    0.470588  0.919598  0.524590  0.000000  0.000000  0.347243  0.253629   
3    0.058824  0.447236  0.540984  0.232323  0.111111  0.418778  0.038002   
4    0.000000  0.688442  0.327869  0.353535  0.198582  0.642325  0.943638   
..        ...       ...       ...       ...       ...       ...       ...   
763  0.588235  0.507538  0.622951  0.484848  0.212766  0.490313  0.039710   
764  0.117647  0.613065  0.573770  0.272727  0.000000  0.548435  0.111870   
765  0.294118  0.608040  0.590164  0.232323  0.132388  0.390462  0.071307   
766  0.058824  0.633166  0.491803  0.000000  0.000000  0.448584  0.115713   
767  0.058824  0.467337  0.573770  0.313131  0.000000  0.453055  0.101196   

            7  
0    0.483333  
1    0.166667  
2    0.183333  
3    0.000000  
4    0.200000  
..        ...  
763  0.700000  
764  0.100000  
765  0.150000  
766  0.433333  
767  0.033333  

[768 rows x 8 columns]

In [6]:
y = [[i] for i in diabetes['Outcome']]
X = np.array(df)

In [7]:
X.shape

(768, 8)

In [33]:
##### Update this Class #####

class Perceptron(object):
    
    def __init__(self, rate = 0.01, niter = 10):
        self.rate = rate   
        self.niter = niter
    
    def sigmoid(self, x):
        return 1 / (1 +np.exp(-x))
    
    def sigmoid_derivative(self, x):
        sx = self.sigmoid(x)
        return sx * (1-sx)

    def fit(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """
    

        # Randomly Initialize Weights
        weights = 2 * np.random.random((8,1)) -1

        for i in range(self.niter):
            # Weighted sum of inputs / weights
            weighted_sum = np.dot(X, weights)
            
            # Activate!
            activated_output = self.sigmoid(weighted_sum)
            
            # Cac error
            error = y - activated_output
            
            adjustments = error * self.sigmoid_derivative(weighted_sum)
            
            # Update the Weights
            weights += np.dot(X.T, adjustments)
        return activated_output


    def predict(self, X):
        """Return class label after unit step"""
        return activated_output

In [35]:
pn = Perceptron(.01, 10)
pn.fit(X,y)


array([[5.91463439e-09],
       [9.06407291e-07],
       [3.96728144e-08],
       [1.07215469e-06],
       [1.45090943e-07],
       [2.00169604e-07],
       [2.71625153e-06],
       [6.49052363e-05],
       [3.49354580e-09],
       [9.58889888e-08],
       [1.13386277e-08],
       [3.02621878e-09],
       [5.39162191e-09],
       [2.10143875e-08],
       [1.44185056e-08],
       [2.54723457e-04],
       [3.45999258e-09],
       [1.13426649e-07],
       [2.51722768e-06],
       [7.92384592e-08],
       [2.66179755e-09],
       [1.34806842e-08],
       [2.86718650e-10],
       [1.26754819e-08],
       [2.52138415e-10],
       [1.89163688e-08],
       [6.35380629e-09],
       [1.50650079e-06],
       [3.87792752e-09],
       [8.80974909e-09],
       [1.41854273e-08],
       [8.41008425e-09],
       [3.40359410e-06],
       [1.12905963e-07],
       [9.52162718e-09],
       [4.69260203e-07],
       [9.58476206e-09],
       [1.10643457e-08],
       [1.00493309e-07],
       [7.60413393e-09],


## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?